name: flutter_sunmi_printer_example
description: Demonstrates how to use the flutter_sunmi_printer plugin.
publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sunmi_printer:
    path: ../
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/rabbit_black.jpg
